const mockProducts = [
  {
    id: 1,
    title: "사과",
    description: "신선하고 달콤한 사과입니다.",
    images: "https://via.placeholder.com/300x200?text=사과",
    origin: "경북 영주",
    harvestDate: "2025-05-10",
    weight: "500g",
    category: "과일",
  },
  {
    id: 2,
    title: "당근",
    description: "유기농 당근으로 건강한 맛을 즐기세요.",
    images: "https://via.placeholder.com/300x200?text=당근",
    origin: "전남 나주",
    harvestDate: "2025-05-08",
    weight: "700g",
    category: "채소",
  },
  {
    id: 3,
    title: "배",
    description: "과즙 가득한 배입니다.",
    images: "https://via.placeholder.com/300x200?text=배",
    origin: "충남 아산",
    harvestDate: "2025-05-01",
    weight: "600g",
    category: "과일",
  },
  {
    id: 4,
    title: "토마토",
    description: "신선한 방울토마토, 샐러드에 딱 좋아요.",
    images: "https://via.placeholder.com/300x200?text=토마토",
    origin: "경남 밀양",
    harvestDate: "2025-04-28",
    weight: "300g",
    category: "채소",
  },
  {
    id: 5,
    title: "오렌지",
    description: "비타민C 가득한 오렌지입니다.",
    images: "https://via.placeholder.com/300x200?text=오렌지",
    origin: "제주도",
    harvestDate: "2025-05-12",
    weight: "800g",
    category: "과일",
  },
  {
  id: 6,
  title: "상추",
  description: "신선한 상추로 식탁을 풍성하게!",
  images: "https://via.placeholder.com/300x200?text=상추",
  origin: "강원도 평창",
  harvestDate: "2025-05-14",
  weight: "400g",
  category: "채소",
}
]

export default mockProducts;
